# Generated by Django 5.2.5 on 2025-09-13 11:44

import accounts.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('mastodon_instance', models.CharField(blank=True, max_length=200)),
                ('mastodon_token', accounts.fields.EncryptedTextField(blank=True)),
                ('bluesky_handle', models.CharField(blank=True, max_length=100)),
                ('bluesky_app_password', accounts.fields.EncryptedTextField(blank=True)),
                ('crosspost_mastodon', models.BooleanField(default=False)),
                ('crosspost_bluesky', models.BooleanField(default=False)),
                ('last_crosspost_error', models.TextField(blank=True)),
                ('last_crosspost_error_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
