# Generated by Django 5.2.5 on 2025-09-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mastodon_char_limit',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
