# Generated by Django 5.2.5 on 2025-09-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_mastodon_char_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Optional short bio displayed on your archive page'),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_archive',
            field=models.BooleanField(default=False, help_text='If true, a public archive/profile page is enabled'),
        ),
    ]
