# Generated by Django 5.2.5 on 2025-09-17 12:25

import accounts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_bio_profile_show_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crosspost_status_cafe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_cafe_default_face',
            field=models.CharField(blank=True, help_text='Optional default emoji code to use when cross‑posting (e.g. 🙂)', max_length=8),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_cafe_password',
            field=accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='status_cafe_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
