# Generated by Django 5.2.5 on 2025-09-17 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_crosspost_status_cafe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status_cafe_default_face',
        ),
    ]
