# Generated by Django 5.2.5 on 2026-02-19 21:13

import accounts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_status_cafe_default_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crosspost_tumblr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='tumblr_access_token',
            field=accounts.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tumblr_blog_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
