# Generated by Django 5.2.5 on 2026-03-07 21:20

import accounts.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_crosspost_tumblr_profile_tumblr_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='crosspost_piclog_blue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='piclog_blue_email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='piclog_blue_password',
            field=accounts.fields.EncryptedTextField(blank=True),
        ),
    ]
