# Generated by Django 5.2.5 on 2026-03-08 02:35

import accounts.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_crosspost_piclog_blue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tumblr_refresh_token',
            field=accounts.fields.EncryptedTextField(blank=True),
        ),
    ]
