# Generated by Django 5.2.5 on 2025-08-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether_notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
