# Generated by Django 5.2.5 on 2025-09-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aether_notes', '0004_note_text_to_textfield_and_views_noteview_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='noteview',
            new_name='aether_note_device__2b821b_idx',
            old_name='aether_notes_noteview_device_created_idx',
        ),
    ]
