# Generated by Django 5.2.5 on 2025-09-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether_notes', '0005_rename_aether_notes_noteview_device_created_idx_aether_note_device__2b821b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='created_device_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
