# Generated by Django 5.2.5 on 2025-09-01 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether_notes', '0006_note_created_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='flags',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='NoteFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_flags', to='aether_notes.note')),
            ],
            options={
                'indexes': [models.Index(fields=['device_id', 'created_at'], name='aether_note_device__7b664c_idx')],
                'constraints': [models.UniqueConstraint(fields=('note', 'device_id'), name='unique_note_device_flag')],
            },
        ),
    ]
