# Generated by Django 5.2.5 on 2025-09-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether_notes', '0007_note_flags_noteflag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
