# Generated by Django 5.2.5 on 2025-09-20 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether_notes', '0009_note_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteCrosspost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('mastodon', 'Mastodon'), ('bluesky', 'Bluesky')], max_length=20)),
                ('remote_id', models.CharField(blank=True, max_length=200)),
                ('remote_url', models.URLField(blank=True, max_length=500)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossposts', to='aether_notes.note')),
            ],
            options={
                'indexes': [models.Index(fields=['network', 'status'], name='aether_note_network_15c4b3_idx')],
                'constraints': [models.UniqueConstraint(fields=('note', 'network'), name='unique_note_network_crosspost')],
            },
        ),
    ]
