# Generated by Django 5.2.5 on 2025-09-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether_notes', '0010_notecrosspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notecrosspost',
            name='status',
            field=models.CharField(db_index=True, default='success', max_length=20),
        ),
    ]
