# Generated by Django 5.2.5 on 2025-10-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether_notes', '0011_alter_notecrosspost_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
