# Generated by Django 5.2.5 on 2026-03-07 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether_notes', '0012_note_is_draft_note_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='note_images/'),
        ),
        migrations.AddField(
            model_name='note',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Alt text for accessibility', max_length=1000),
        ),
        migrations.AlterField(
            model_name='notecrosspost',
            name='network',
            field=models.CharField(choices=[('mastodon', 'Mastodon'), ('bluesky', 'Bluesky'), ('tumblr', 'Tumblr'), ('piclog_blue', 'Piclog.blue')], max_length=20),
        ),
    ]
