# Generated by Django 5.2.5 on 2026-03-08 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether_notes', '0013_note_image_note_image_alt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image_hq',
            field=models.FileField(blank=True, null=True, upload_to='note_images_hq/'),
        ),
    ]
