# Generated by Django 5.2.5 on 2026-03-08 02:52

import aether_notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aether_notes', '0014_note_image_hq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=aether_notes.models._note_image_path),
        ),
        migrations.AlterField(
            model_name='note',
            name='image_hq',
            field=models.FileField(blank=True, null=True, upload_to=aether_notes.models._note_image_hq_path),
        ),
    ]
