# Generated by Django 5.2.5 on 2026-08-16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aether_notes", "0015_alter_note_image_alter_note_image_hq"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostQueueSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("interval_value", models.PositiveIntegerField(default=24, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)])),
                ("interval_unit", models.CharField(choices=[("hours", "Hours"), ("days", "Days")], default="hours", max_length=5)),
                ("paused", models.BooleanField(default=False)),
                ("next_publish_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="post_queue_settings", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("interval_value__range", (1, 365))), name="post_queue_interval_range"),
                ],
            },
        ),
        migrations.CreateModel(
            name="QueuedNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("position", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("crosspost_mastodon", models.BooleanField(default=False)),
                ("crosspost_bluesky", models.BooleanField(default=False)),
                ("crosspost_status_cafe", models.BooleanField(default=False)),
                ("crosspost_tumblr", models.BooleanField(default=False)),
                ("crosspost_piclog_blue", models.BooleanField(default=False)),
                ("status_cafe_face", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("note", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="queue_entry", to="aether_notes.note")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="queued_notes", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ("position", "id"),
                "indexes": [models.Index(fields=["user", "position"], name="aether_note_user_id_d9505c_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "position"), name="unique_user_queue_position"),
                    models.CheckConstraint(condition=models.Q(("position__gte", 1)), name="queued_note_positive_position"),
                ],
            },
        ),
    ]
